### PR TITLE
feat: add div

### PR DESCRIPTION
**Pull request by Hash-Ezz**

### CODE REVIEW

**Review by YasserEsam — CHANGES_REQUESTED** [review]
Write good code please

**Review by Ahmed-Sitl — APPROVED** [review]
Good

**Comment by Hash-Ezz** [comment]
ok

**Review by YasserEsam — COMMENTED** [review]
Thanks I like it

**Comment by YasserEsam** [comment]
That is fucking greate

**Comment by Ahmed-Sitl** [comment]
good

**Pull request merged**
